// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "chordDHT.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class chordDHTHandler : virtual public chordDHTIf {
 public:
  chordDHTHandler() {
    // Your initialization goes here
  }

  void notify(const NODE& node, const NODE& pred) {
    // Your implementation goes here
    printf("notify\n");
  }

  void get_pred(NODE& _return, const NODE& node) {
    // Your implementation goes here
    printf("get_pred\n");
  }

  void find_successor(NODE& _return, const int64_t id) {
    // Your implementation goes here
    printf("find_successor\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<chordDHTHandler> handler(new chordDHTHandler());
  ::std::shared_ptr<TProcessor> processor(new chordDHTProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

